- highkeep/Lislia_Goldtune.lua
QuestReward() is missing a 0 arg and was attempting to give itemid 300 and 0 exp.
https://ptb.discord.com/channels/1133452007412334643/1158887102126227616/1163237994942173204
> Fixed Lislia Goldtune quest reward

- neriakc/Lokar_To-Biath.lua
This quest was updated from takp quests in this commit: https://github.com/SecretsOTheP/quests/commit/c7de1ea258f2ccd0c13c5b66dbe5d982fce3db38
I am assuming the intent was to make it comparable to the source: https://github.com/EQMacEmu/quests/blob/main/neriakc/Lokar_To-Biath.lua#L48-L50
If that was the intent, this line missed getting deleted. This results in 10% extra faction, but more noticeably two messages that the same faction improved on turn in.
> Correct Redwine faction reward

- timorous/Avatar_of_Water.lua
This allows multiple clerics to turn in triumvirate if one of them missed their chance for whatever reason, instead of creating a race for the mob by possibly blocked clerics sniping the next cleric's chance.
> Prevent Cleric epic deadlock / grief situation

- timorous/Avatar_of_Water.lua
- timorous/Omat_Vastsea.lua
In the event a Cleric attempting their epic is killed by spawned Faydedar, the turn in NPCs are killed by spawned Faydedar, or if another Cleric attempts to use the NPC after their own failed attempt (blocking the current quester) - these changes will allow a turn in of interim step items to Omat Vastsea in order to respawn quest NPCs.  Omat will return the Cleric's item and spawn the appropriate NPC for the final epic turn in.  This effectively, prevents Clerics from griefing one another due to botched prior turn ins.
> Support for Repopping Cleric Epic Mobs

- timorous/Barrel_Barge.lua
- timorous/Bloated_Belly.lua
- timorous/Captains_Skiff.lua
- timorous/Island_Shuttle.lua
- timorous/Maidens_Voyage.lua
- timorous/Muckskimmer.lua
- timorous/Shuttle_I.lua
- timorous/Shuttle_II.lua
- timorous/Shuttle_III.lua
- timorous/Shuttle_IV.lua
Boats in instanced timorous are signaling and modifying global states simultaneously with the non-instanced timorous zone.  This is causing strange behaviors as multiple sets of boats are active at the same time attempting to coordinate with each other.  This patch will prevent instanced boats from spawning and interacting with the world.
> Prevent boats in timorous instances from spawning

- timorous/Barrel_Barge.lua
- timorous/Bloated_Belly.lua
- timorous/Captains_Skiff.lua
- timorous/Island_Shuttle.lua
- timorous/Maidens_Voyage.lua
- timorous/Muckskimmer.lua
- timorous/Shuttle_I.lua
- timorous/Shuttle_II.lua
- timorous/Shuttle_III.lua
- timorous/Shuttle_IV.lua
Lua code for boats was not evaluating 0xFFFFFFFF as max uint, rather as -1.  As a result, all boats in timorous were despawning. 
Changed the condition for all boats, verified on test server.
> Updated instance detection for boats in timorous

- fear_instanced/Dread.lua
- fear_instanced/Fright.lua
- fear_instanced/Terror.lua
- fearplane/Dread.lua
- fearplane/Fright.lua
- fearplane/Terror.lua
During the recent TAKP peq_expansion update, expansion values changed from Classic = 1 to Classic = 0 and subsequently all expansions values were decremented by 1. Several areas rely on these expansion values by integer and these fearplane and fear_instanced scripts were causalities of the change.  Modified scripts to match TAKP content system updates.
> Changed expansion check in fearplane/fear_instanced to new TAKP content system

- timorous/an_Iksar_master.lua
The gating logic was causing the `test/trial of patience` dialog to not be able to trigger.
> Timorous Deep - an_Iksar_master dialogue fix

- lua_modules/self_found_enchant_bars.lua
I initially set the level requirements to that of the enchanter spell level (49).
Level requirements that high obviate a number of items created via tradeskills, notably silvered weapons, which are on par with lvl 20ish weapons in terms of damage plus they are magical and are essentially useless at level 49. So this pr sets the level requirement of blacksmithing metals to 20 to make tradeskill equipment accessible at a more appropriate level.
> Tweak level requirements of self-found metal enchanting

- lua_modules/self_found_enchant_bars.lua
Enchanted gold and platinum are used in a number of mid-20s quests, notably cleric and shadow knight sol ro quests. Adjusted gold/plat bar levels in accordance.
> Adjust required lvl for self-found bar enchant

- lua_modules/items.lua
Crude quest turn in support for stacked items like goblin skins, but at the library level
Note: This has not been tested in terms of will it give back stacks that aren't right, etc. This is basically a small QoL change with sharp edges if its not the right kind of turn in, but honestly its fine because it would eat the items previously.
> Crude turnin support for stacked items at the library level

- freporte/Efreeti_Weapon_Polisher.lua
- Added mirrored quests to restore polished/sharpened Efreeti items back to their original item.
- Changed from `SummonCursorItem()` to `QuestReward()`.
- Since the original items are stackable, `SummonCursorItem(item, 1)` would summon a full stack to their cursor. We just want to give back 1.
-  Added `return_items()` check.
- Allows players to revert their Efreeti items so they can be turned in for their Sky quests after they have collected all the other quest pieces.
- Tested on local server and verified each item works both ways, and 1 item is received in each direction.
- Return items is now working as expected.
> Add quest to un-polish Efreeti items

- lua_modules/items.lua
Tested non quest items:
- Gave 20x Bone Chips. Killed. Looted 20x Bone Chips
- Gave 3x Bone Chips. Killed. Looted 3x Bone Chips
- Gave Puppet Strings (0 charges). Killed. Looted Puppet Strings (0 charges)
- Gave Mask of Tinkering (-1 charges). Killed. Looted Mask of Tinkering.
Tested Quest Completion:
- Tested standard Quest Turn (Red Dragon Scale + White Dragon Scales + Metal Bits). Success.
- Tested repeatable Quest Turn in (20 Green Goblin Skins). 20x Success.
- Tested partial turn in (1 Mt Death Mineral Salts). Added 1 charge to Quest Loot. Second hand-in is success & deletes Quest Loot.
- Tested full + partial turn in (3 Mt Death Mineral Salts). 1 Success. Added 1 charge to Quest Loot.
> Update charges logic in quest npcs

- frontiermtns/encounters/FMCycle.lua
Requested here: https://discord.com/channels/1133452007412334643/1301598028905451600
Tested by running around Frontier Mtns after killing one and always found another.  Depending on how random() works, there might be a 1% chance for a non-named
The loot drops are not 100% and the loot doesn't seem OP imo, so this seems like a solid suggestion to make something more fun and get some interesting items in the economy.
Left in the random functionality in case we want to scale it back from 100%
> Frontier Mtns - Increase probability for named cycle spawn to 100%

- global/Priest_of_Discord.lua
Removing the respec dialogic, rather than having it disabled. So it doesn't confuse people on PQDI.
> Fix NG+ typo and removing unused respec script

- global/Priest_of_Discord.lua
- Added 'Hail' text for NG+ and gender change.
- Adjusted trigger text to use `[reborn]` keyword, instead of `[newgame plus]`
- Fixed `[challenges]` trigger to allow S/SF/HC to see the response, since `dd516de` re-enabled this in other dialogue paths.
> New intro text for rebirth and gender change.

- global/Priest_of_Discord.lua
- lua_modules/newgameplus.lua
- PoD now lets people do class/race changes based on what they have unlocked.
- Easy to add/remove NG+ options at the top of the `newgameplus.lua` module (see below). PoD updates automatically.
```lua
local barbarianPaladinDiscovered = ng.IsBarbarianPaladinUnlocked(e);
-- Barbarian Paladin race-change. Available to non-barbarian paladins.
configs[2] = {
name = "(Race Change) Barbarian Paladin",
minLevel = 30,
isRaceChange = true,
curClass = "Paladin",
mustRaceChange = "Barbarian",
setLevel = 10,
discovered = barbarianPaladinDiscovered
};
-- Barbarian Paladin class-change. Available to non-paladin barbarians.
configs[3] = {
name = "(Class Change) Barbarian Paladin",
minLevel = 30,
isClassChange = true,
curRace = "Barbarian",
mustClassChange = "Paladin",
setLevel = 10,
setLevel2 = 10, …
```
> Feature - NG+ Module, support for level 30 race/class changes, etc

- lua_modules/newgameplus.lua
If you didn't already change locally, this is all that's needed for level 1 NG+Barb Pally, if that's the plan still.
> Require level 1 for NG+Barb Pally

- global/Priest_of_Discord.lua
- lua_modules/title_manager.lua
**Requires Server PR merged https://github.com/SecretsOTheP/EQMacEmu/pull/249**
- Added lua module for doing title management.
- Integrated with PoD for now. (Say `name`, or `title`, etc). Added hail text.
- Uses a rules system that control validation and formatting.
- Currently supports `the Reborn` title and the Roman numeral system.
- Players with existing custom surnames will still keep those even if they use this NPC. Their surnames will be treated like a regular surname to mix and match with the titles. Still has a 31 char limit.
- Also allows removing player's surnames. (they still have a 7 day cooldown to make a new /surname).
Full list of allowed combinations is pretty much this. Surname is optional, but must come first.
- [surname] the Reborn
- [surname] the Reborn III
- …
> Feature - Lua Title Management

- lua_modules/self_found_enchant_bars.lua
The prices to do Self-Found Enchanting became prohibitively expensive for the required materials for standard skillups paths due to "tipflation" (which feels all too real in Current Year).
This patch lowers the NPC tip down from 10-300pp/ea to ~1pp/ea.
Especially because it's also ~4x harder to MAKE plat on self-found, when we can't sell items for plat in EC. So it's an order of magnitude difference in cost per skill.
Thorondor provided several good math summaries about it, and it does seem very high. Here's one excerpt:
- Allow grouped SF players be able to cast Enchant spells on each other. If the target has the reagents on them, it will consume the reagents from the target and give them the summoned bar/item instead.
- Make it so the SF Enchanter NPC instead of requiring a tip, …
> Removing Price Gouging from Self Found Enchanting

- cabeast/Belner_Snuckery.lua
- commons/Noresa_Sparkle.lua
- erudnint/Sothure_Gemcutter.lua
- felwithea/Merchant_Silspin.lua
- freportn/Amber.lua
- gfaydark/Merchant_Kweili.lua
- kaladimb/Aanina_Rockfinder.lua
- lua_modules/self_found_enchant_bars.lua
- lua_modules/self_found_imbue_gems.lua
- lua_modules/self_found_mind_melt.lua
- lua_modules/self_found_rebreathers.lua
- neriaka/Canarie.lua
- neriakb/Zartox_Ru-Soe.lua
- qeynos2/Ziska_Ironforge.lua
- Allows SF+ players to also access SF quests. (Bar/Vial enchanting, etc)
- Enables multi-turn-in support for SF enchanting. (Note: I tested this pretty extensively and it's working)
> Fix: Several SF quests (enchanting, rebreathers, etc) to detect SF+

- iceclad/Avatar_of_Below.lua
- iceclad/General_Bragmur.lua
- thurgadinb/#Dain_Frostreaver_IV.lua
- Shawl 8 can no longer be skipped/multi-quested by having someone else spawn the event with their crafted materials.
- Shawl 8 final turn-in changed to prevent a stranger sniping the reward. Multiple participants to complete it upon success:
- Avatar of Below will no longer despawn instantly after the first player to turn in Shawl 7.
- Avatar of Below now requires the Shawl 7 + Approved Issue Kit (instead of just the Shawl) to complete the final turn in, as proof of doing all the crafting for Shawl 8.
- General Bragmur now returns the Approved Issue Kit when you start the escort (So you will have it to hand it to Avatar of Below upon success).
These tweaks were designed to prevent bad behavior caused by how someone could 'skip' the whole Shawl 8 if they just waited for the guy to spawn …
> Shawl 8 - Disable MQ, fix sniping, allow multi-turn-in

- eastwastes/#Garadain_Glacierbane.lua
- eastwastes/Dobbin_Crossaxe.lua
- eastwastes/Garadain_Glacierbane.lua
Patch Notes
- (Ring 7) The non-quest version of Dobbin Crossaxe will now return Ring 7 instead of eating it.
- (Ring 8) Garadain Glacierbane no longer despawns after handing him Chief Ry`Gorrs Head.
- (Ring 8) All versions of Garadain Glacierbane now accept Chief Ry`Gorrs Head.
Changelog
- ##Garadain_Glacierbane.lua (War Part 2)
- Removed depop() on Chief Ry`Gorrs Head.
- #Garadain_Glacierbane.lua (War Part 1)
- New file.
- Now accepts Chief Ry`Gorrs Head.
- Returns items instead of eating.
- Garadain_Glacierbane.lua (Default)
- Now accepts Chief Ry`Gorrs Head.
- Whitespace fixed (Mac -> Windows).
- Dobbin_Crossaxe.lua (Default)
- New file.
- Returns items instead of eating.
> Improved Ring 7 and Ring 8 scripts.

- eastwastes/#Peffin_Ambersnow.lua
- eastwastes/Peffin_Ambersnow.lua
Fixed issues that would cause Peffin's guards to infinitely grow in number over time.
- #Peffin's guards will now depop after #Peffin's death.
- #Peffin's guards (from previous #Peffins) will now depop when #Peffin spawns with a fresh set of Guards, if for any reason they are still alive. Prevents duplicate guards up at the same time.
> [Ring9] Peffin's guard will now depop after Peffin's death

- greatdivide/encounters/Ring10.lua
- Narandi now drops the Ring War bonus reward items (based on which dwarves survived)
- This also prevents any abuse by previous ringbearers that may try to snipe hand-ins with an old Shorn Head.
This is so the rewards can be obtained by the appropriate self-found members of the raid, rather than being all rewarded to the ringbearer and then unable to trade.
> [Ring10] Final rewards now drop from Narandi instead (self-found compatibility)
